apiVersion: v1
kind: Namespace
metadata:
  name: pdw-ci-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: pdw-service
  namespace: pdw-ci-namespace
spec:
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: cont-http-port
      name: svc-http-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdw-deployment
  namespace: pdw-ci-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdw-deployment-label
  template:
    metadata:
      labels:
        app: pdw-deployment-label
    spec:
      containers:
        - name: pdw-container
          image: $DOCKER_ACCOUNT/pokemon-deck-wizard:0.1.$CIRCLE_BUILD_NUM
          ports:
            - containerPort: 8080
              name: cont-http-port
