apiVersion: v1
kind: Namespace
metadata:
  name: pdw-ci-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: pdw-load-balancer
  namespace: pdw-ci-namespace
spec:
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: pdw-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdw-deployment
  namespace: pdw-ci-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdw-app
  template:
    metadata:
      labels:
        app: pdw-app
    spec:
      containers:
        - name: pdw-container
          image: $IMAGE_TAG
          ports:
            - containerPort: 8080
