apiVersion: v1
kind: Namespace
metadata:
  name: ci-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: app-ci-service
  namespace: ci-namespace
spec:
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-container-port
      name: http-service-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ci-deployment
  namespace: ci-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ci
  template:
    spec:
      containers:
        - name: app-ci-container
          image: $DOCKER_ACCOUNT/pokemon-deck-wizard:0.1.$CIRCLE_BUILD_NUM
          ports:
            - containerPort: 8080
              name: http-container-port
